import { randomUUID } from "crypto";
import { NextResponse } from "next/server";

import {
  findUserByAccountNumber,
  findUserByPartnerUserId,
  findUserByEmail,
} from "@/lib/demo-bank-store";
import { initVisualEnroll, VisualApiError } from "@/lib/visual-api";
import { sendReenrollLinkEmail } from "@/lib/email-service";

/**
 * POST /api/demo-bank/agent/admin-reset
 *
 * Admin-privileged: no OTP required (admin is already authenticated via the
 * SaaS admin panel). Looks up user by accountNumber | partnerUserId | email,
 * generates a fresh one-use enroll session, emails the link, and returns it
 * so the admin can also copy-paste it directly.
 */
export async function OPTIONS() {
  return new NextResponse(null, { status: 204 });
}

export async function POST(request: Request) {
  try {
    const body = (await request.json()) as { query: string; triggeredBy?: string };
    const query = String(body.query || "").trim();
    const triggeredBy = String(body.triggeredBy || "Admin Console").trim();

    if (!query) {
      return NextResponse.json({ message: "query (account number, userId, or email) is required." }, { status: 400 });
    }

    // Find user — try account number first (6 digits), then partnerUserId, then email
    let user =
      /^\d{6}$/.test(query)
        ? await findUserByAccountNumber(query)
        : null;
    if (!user) user = await findUserByPartnerUserId(query);
    if (!user) user = await findUserByEmail(query);

    if (!user) {
      return NextResponse.json({ message: `No user found for "${query}".` }, { status: 404 });
    }

    // Generate a fresh visual-password enroll session
    const enroll = await initVisualEnroll({
      partnerUserId: user.partnerUserId,
      state: randomUUID(),
    });

    // Auto-send email (non-fatal — link is still returned even if email fails)
    let emailSent = false;
    try {
      await sendReenrollLinkEmail(user.email, user.fullName, enroll.enrollUrl, triggeredBy);
      emailSent = true;
    } catch (emailErr) {
      console.warn("[admin-reset] email send failed:", emailErr instanceof Error ? emailErr.message : emailErr);
    }

    console.log(
      `[admin-reset] link generated by "${triggeredBy}" for ` +
      `partnerUserId="${user.partnerUserId}" accountNumber="${user.accountNumber}" → ${user.email}`,
    );

    return NextResponse.json({
      ok: true,
      user: {
        fullName: user.fullName,
        emailMasked: maskEmail(user.email),
        accountNumber: user.accountNumber,
        partnerUserId: user.partnerUserId,
      },
      enrollUrl: enroll.enrollUrl,
      emailSent,
      expiresInMinutes: 15,
      message: emailSent
        ? `Reset link emailed to ${maskEmail(user.email)} and is ready to copy.`
        : `Email send skipped (dev mode). Copy the link below.`,
    });
  } catch (err) {
    if (err instanceof VisualApiError) {
      return NextResponse.json({ message: err.message }, { status: err.statusCode });
    }
    console.error("[admin-reset]", err);
    return NextResponse.json({ message: "Failed to generate reset link." }, { status: 500 });
  }
}

const maskEmail = (email: string) => {
  const [local, domain] = email.split("@");
  if (!local || !domain) return email;
  return local.slice(0, 2) + "***@" + domain;
};
